### ISSUE TITLE
New builds ?

### ISSUE THREAD

**Issue by huertgenwald** [daidodo/diablo_edit#17]
Is this project still alive ?

Since savegames of  V2.4 are incompatible with the current version V2.3. AFAIK

TiA

**Comment by daidodo** [comment]
Sorry, I was on something else. Will come back once free.
Also I'm happy to accept PRs if you want to help.

Thanks!

**Comment by daidodo** [comment]
@huertgenwald, could you share a d2s or character save file for PTR2.4?
I haven't played the game for a while and missed the public test.
Thanks!

**Comment by huertgenwald** [comment]
Well, the patch will hit live servers tomorrow. But i found an old PTR savegame. Changes in d2s should be small, but people in twitch chat said, that v.2.3 can't load v2.4 file without several error messages. So  maybe editor needs changes too ?
[PTR-save.zip](https://github.com/daidodo/diablo_edit/files/8484824/PTR-save.zip)

HtH, TiA

**Comment by daidodo** [comment]
With a few changes, I'm able to read the character. But one issue is that the name is empty.

![image](https://user-images.githubusercontent.com/8170176/163291174-c3a4f1d0-d019-48de-9e7f-c41fc9b61c44.png)

Can you confirm the name and other values?
Thanks!

**Comment by daidodo** [comment]
Please try [v0.11](https://[github.com/daidodo/diablo_edit/releases/tag/0.11) and tell me if you still have questions.
Thanks!

**Comment by huertgenwald** [comment]
Tested with my current toon, just converted to v2.4. Name shows up, no obvious problems right now.

**Comment by Drendar99** [comment]
Hi. I found a few oddities when I tested it. A newly created 2.4 character loads just fine, but when I save I get a "Character and file name are different, continue?" message. Then the name disappears after saving. 

However, the character still has his name in the came, and the edits I made are there. So, push comes to shove, it works for new 2.4 characters.

The second oddity is that one character I had before 2.4 can't be open now. I get a "Corpse data format error" and can't edit anything. Oddly,this now also happens when I try to open the character with version 0.10. The really weird thing is that I can open a different 2.3 created character (more recently created, if that matters) without issue.

Still, at the end of the day, it's working for new 2.4 characters, which is what I most need, so thank you for giving us this!

**Comment by daidodo** [comment]
@Drendar99, thanks for the feedback!

Could you share character files with the issues?

**Comment by Drendar99** [comment]
Sure! (Sorry, I didn't think of that right off.) Okay, hmm, Github's saying that d2s files are supported. Is there something I'm missing here? (Literally just joined earlier today.)

**Comment by Drendar99** [comment]
@daidodo Hey, I just saw how you added a commit about an issue with personalized item names, so I tried a little experiment: 

For the character I couldn't open with 0.11, I moved the personalized item to the shared stash, presumably removing it from the save file, and boom -- I was able to open and edit that character. (I still saw the little "name is different" message on saving, but like before, that doesn't seem to actually stop the editor from working. The edits were reflected when I started the game again.)

So, there's that, if it helps to know.

**Comment by daidodo** [comment]
@Drendar99, please try [v0.14](https://github.com/daidodo/diablo_edit/releases/tag/0.14).

"Drendar" wasn't loaded because one of the items (Two-handed sword) is personalised.
Seems PTR2.4 has changed all the names (character name, personalised name and ear name).

Please tell me if you have more issues.
Thanks!

**Comment by Drendar99** [comment]
@daidodo Just tried it out. Works with all characters, personalized items or not, and I'm not getting the "different name" message on saving.

Thanks again for all your help!

**Comment by daidodo** [comment]
I'm going to close the issue. But feel free to open new ones if you find other issues.

Thank you all for your contributions!
