### ISSUE TITLE
Golem data format error

### ISSUE THREAD

**Issue by angelvet** [daidodo/diablo_edit#4]
Hi there!

Just want to try your character editor but it fails to load my Diablo II resurrected save file with an error "Golem data format error".

**Comment by angelvet** [comment]
My char d2s file:
[Nigga.zip](https://github.com/daidodo/diablo_edit/files/7259672/Nigga.zip)

**Comment by daidodo** [comment]
@angelvet - Thanks for the feedback!
I've published [release 0.4](https://github.com/daidodo/diablo_edit/releases/tag/0.4) to address the issue.

The root cause is a small change in D2R that mercenary name index can be 0 (in previous versions it's from 1).
Please tell me if you have further questions.
Cheers!

**Comment by angelvet** [comment]
Great! Thanks.
